#!/usr/bin/env bash
set -euo pipefail

# Bootstrap Monster Automation environment from ma-hub.
# Safe to re-run on any laptop.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_DIR="${HOME}/.config/ma-hub"
CONFIG_FILE="${CONFIG_DIR}/config"

echo "=== ma-hub bootstrap ==="
echo "Hub: ${ROOT}"

mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
# Generated by ma-hub bootstrap — do not commit secrets here
MA_HUB_ROOT="${ROOT}"
# Policy: track main (latest). Override for a pin, e.g. MA_HUB_REF=v1.0.0
# MA_HUB_REF=
EOF
echo "Wrote ${CONFIG_FILE}"

chmod +x "${ROOT}/bootstrap/"*.sh
"${ROOT}/bootstrap/install-commands.sh"
"${ROOT}/bootstrap/install-skills.sh"
# shellcheck source=stamp.sh
source "${ROOT}/bootstrap/stamp.sh"
ma_hub_write_stamp "$ROOT"

# Convenience symlinks in ~/bin if present or creatable
BIN_DIR="${HOME}/bin"
mkdir -p "$BIN_DIR"
ln -sfn "${ROOT}/bootstrap/pull.sh" "${BIN_DIR}/ma-hub-pull"
ln -sfn "${ROOT}/bootstrap/ensure-latest.sh" "${BIN_DIR}/ma-hub-ensure-latest"
ln -sfn "${ROOT}/bootstrap/cloud-ensure.sh" "${BIN_DIR}/ma-hub-cloud-ensure"
ln -sfn "${ROOT}/bootstrap/bootstrap.sh" "${BIN_DIR}/ma-hub-bootstrap"
ln -sfn "${ROOT}/bootstrap/install-commands.sh" "${BIN_DIR}/ma-hub-install-commands"
ln -sfn "${ROOT}/bootstrap/install-skills.sh" "${BIN_DIR}/ma-hub-install-skills"
ln -sfn "${ROOT}/bootstrap/install-external-skills.sh" "${BIN_DIR}/ma-hub-install-external-skills"
ln -sfn "${ROOT}/bootstrap/check-local-drift.sh" "${BIN_DIR}/ma-hub-check-drift"
ln -sfn "${ROOT}/bootstrap/install-launch-agent.sh" "${BIN_DIR}/ma-hub-install-launch-agent"
ln -sfn "${ROOT}/bootstrap/install-session-hook.sh" "${BIN_DIR}/ma-hub-install-session-hook"
echo "Symlinks: ma-hub-pull, ma-hub-ensure-latest, ma-hub-cloud-ensure, ma-hub-bootstrap, … → ${BIN_DIR}"

# Daily auto-sync + soft session refresh (macOS / local Cursor)
"${ROOT}/bootstrap/install-launch-agent.sh" || echo "WARN: launch agent not installed"
"${ROOT}/bootstrap/install-session-hook.sh" || echo "WARN: session hook not installed"

echo
echo "=== User Rules (Cursor Settings) ==="
echo "Восстановите личные правила из файла:"
echo "  ${ROOT}/docs/user-rules.md"
echo "Cursor → Settings → Rules → добавьте 4 правила из этого файла."
echo "Без них тон диалога и закон «истина в ma-hub» не восстановится автоматически."
echo
echo "=== Skills ==="
echo "MA-owned: уже установлены из ${ROOT}/skills/"
echo "Внешние (Aaron, Vercel, ponytail…): registry → install-external-skills.sh"
echo "  ${ROOT}/bootstrap/install-external-skills.sh"
echo "  (или weekly ~/bin/update-cursor-weekly.sh)"
echo
echo "=== Drift check ==="
echo "Проверка кэша MA: ${ROOT}/bootstrap/check-local-drift.sh  (или ma-hub-check-drift)"
echo
echo "=== Готово ==="
echo "В чате Cursor: /MA-help"
echo "Стандарты: ${ROOT}/standards/ (VERSION=$(cat "${ROOT}/standards/VERSION"))"
echo "Hub maintenance: ${ROOT}/docs/hub-maintenance.md"
echo "External skills registry: ${ROOT}/registry/external-skills.md"
