#!/usr/bin/env bash
set -euo pipefail

# Make MA commands/skills/standards available on a Cloud Agent VM (or fresh Linux box).
# Idempotent — safe as .cursor/environment.json "install" / update command.
#
# What it does:
#   1) Clone ma-hub if missing (default ~/ma-hub)
#   2) ensure-latest (fetch only if remote moved / stamp stale)
#   3) Install /MA-* into ~/.cursor/commands and ~/.cursor/skills
#   4) Also copy /MA-* into the current project .cursor/commands (slash menu in that repo)
#      without committing them (see templates/gitignore-ma-commands.snippet)
#
# Env:
#   MA_HUB_URL     default https://github.com/MagnumMax/ma-hub.git
#   MA_HUB_ROOT    default ~/ma-hub
#   MA_HUB_REF     optional pin
#   MA_PROJECT_ROOT  project to receive .cursor/commands (default: cwd)
#   MA_SKIP_PROJECT_COMMANDS=1  skip copying into project

MA_HUB_URL="${MA_HUB_URL:-https://github.com/MagnumMax/ma-hub.git}"
MA_HUB_ROOT="${MA_HUB_ROOT:-${HOME}/ma-hub}"
MA_PROJECT_ROOT="${MA_PROJECT_ROOT:-$(pwd)}"

echo "=== ma-hub cloud-ensure ==="
echo "Hub target: ${MA_HUB_ROOT}"
echo "Project:    ${MA_PROJECT_ROOT}"

if [[ ! -d "${MA_HUB_ROOT}/.git" ]]; then
  echo "Cloning ma-hub…"
  mkdir -p "$(dirname "$MA_HUB_ROOT")"
  git clone --depth 1 "$MA_HUB_URL" "$MA_HUB_ROOT"
fi

CONFIG_DIR="${HOME}/.config/ma-hub"
mkdir -p "$CONFIG_DIR"
cat >"${CONFIG_DIR}/config" <<EOF
# Generated by ma-hub cloud-ensure
MA_HUB_ROOT="${MA_HUB_ROOT}"
# MA_HUB_REF=
EOF

chmod +x "${MA_HUB_ROOT}/bootstrap/"*.sh
"${MA_HUB_ROOT}/bootstrap/ensure-latest.sh"

if [[ "${MA_SKIP_PROJECT_COMMANDS:-0}" != "1" && -d "$MA_PROJECT_ROOT" ]]; then
  DEST="${MA_PROJECT_ROOT}/.cursor/commands"
  mkdir -p "$DEST"
  shopt -s nullglob
  for f in "${MA_HUB_ROOT}/commands"/MA-*.md; do
    cp "$f" "${DEST}/$(basename "$f")"
    echo "project command: $(basename "$f")"
  done
  for local_f in "${DEST}"/MA-*.md; do
    base="$(basename "$local_f")"
    if [[ ! -f "${MA_HUB_ROOT}/commands/${base}" ]]; then
      rm -f "$local_f"
      echo "removed obsolete project command: ${base}"
    fi
  done
fi

echo "OK: cloud-ensure complete · standards VERSION=$(cat "${MA_HUB_ROOT}/standards/VERSION" 2>/dev/null || echo '?')"
echo "Reminder: add templates/gitignore-ma-commands.snippet to the project .gitignore"
